import Head from 'next/head'
import Sideber from '../components/Sideber'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Sidebar */}
        <Sideber />

        {/* Main Section */}

        {/* Feed */}

        {/* Widget */}

        {/* Modal */}
      </main>

    </div>
  )
}
