import Head from 'next/head'
import Feed from '../components/Feed'
import Sideber from '../components/Sideber'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main container */}
      <main className='flex min-h-screen max-w-7xl mx-auto'>
        {/* Sidebar */}
        <Sideber />

        {/* Twitter Feed */}
        <Feed />

        {/* Widget */}

        {/* Modal */}
      </main>

    </div>
  )
}
